security:
  jwt:
    token:
      secret-key: 53cr37
springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: DelAgenda
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DelAgenda_db
    username: postgres
    password: gusta
